# Generated by Django 6.0.5 on 2026-05-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prodct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brand', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('countInStock', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
