# Generated by Django 6.0.5 on 2026-06-02 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_prodct_countinstock_alter_prodct_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('non_binary', 'Non-binary'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city_province', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=30)),
                ('security_question', models.CharField(blank=True, max_length=255)),
                ('security_answer_hash', models.CharField(blank=True, max_length=255)),
                ('language_preference', models.CharField(blank=True, default='en', max_length=50)),
                ('time_zone', models.CharField(blank=True, default='UTC', max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('occupation_school', models.CharField(blank=True, max_length=255)),
                ('social_links', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
